name: AWS Backend CI

on:
  push:
    branches:
      - '*'

jobs:
  build-terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tf code in runner environment
        uses: actions/checkout@v3.5.2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/modules/backend

      - name: Analyze Terraform code
        run: terraform validate
        working-directory: ./terraform/modules/backend
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan    
        env:
          TF_VAR_backend: '{ bucket_name = "tf-backend-test", region = "eu-west-1",
           dynamodb_table = "tf-backend-test", bucket_sse_algorithm = "AES256" }'
        working-directory: ./terraform/modules/backend
  run-test:
    needs: "build-terraform-plan"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
      working-directory: ./test

    - name: Test
      run: go test -v ./backed_test.go
      working-directory: ./test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_CQS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CQS }}