name: "Cluster Deployment"
 
on:
  push:
    branches:
      - main
env:

 TF_LOG: INFO
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
jobs:
  cluster-deployment:
   name: "Deploying Cluster and tasks"
   #needs: common-infra-deployment
   runs-on: ubuntu-latest

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Configure AWS Credentials Action For GitHub Actions
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-west-2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2.0.2

     - name: Backend Configuration
       run: |
         cat <<EOF >backend.hcl
         terraform {
           backend "s3" {
             bucket         = "terraform-backend-state-incode-demo"
             key            = "state/resource.tfstate"
             region         = "us-east-1"
             dynamodb_table = "resource-backend-lock"
             profile        = "sre-admin"
           }
         }
         EOF
       working-directory: terraform

     - name: Terraform init
       id: init
       run: terraform init -backend-config="backend.hcl"
       working-directory: ./terraform

     - name: Terraform format
       id: fmt
       run: terraform fmt -check
       working-directory: ./terraform

     - name: Terraform validate
       id: validate
       run: terraform validate
       working-directory: ./terraform
 
     - name: Terraform plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -var-file=terraform.tfvars -no-color -input=false
       continue-on-error: true
       working-directory: ./terraform

     - name: Terraform apply
       id: apply
       run: terraform apply -var-file=terraform.tfvars -auto-approve
       working-directory: ./terraform