name: Deploy Common Infra
 
on:
  push:
    branches:
      - main
env:

 TF_LOG: INFO
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
jobs:
  common-infra-deployment:
   name: "Deploying all the infra who is in common and required for deploying the custer. For now , backend and ecr"
   runs-on: ubuntu-latest

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Configure AWS Credentials Action For GitHub Actions
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-west-2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2.0.2
    
     - name: Terraform init
       run: terraform init 
       working-directory: ./terraform

     - name: Terraform format
       run: terraform fmt -check
       working-directory: ./terraform

     - name: Terraform validate
       run: terraform validate
       working-directory: ./terraform
 
     - name: Terraform plan
       run: terraform plan -var-file=terraform.tfvars -no-color -input=false
       working-directory: ./terraform

     - name: Terraform apply
       run: terraform apply -target=module.backend -target=module.aws_ecr_repository -var-file=terraform.tfvars -auto-approve
       working-directory: ./terraform
